### ISSUE TITLE
Adding translation files for the french language

### ISSUE THREAD

**Issue by peninonwilliam** [netgen/TagsBundle#101]
I just want to add the translation files so that the French language is supported natively.

**Comment by emodric** [comment]
Hi @peninonwilliam ! 

Why don't you create a pull request with french translation files? :)

**Comment by peninonwilliam** [comment]
Hi @emodric modric

it seems that I can not push the branch of work on the deposit


`git push origin add-fr-translation                                                                                                                                                                                           
Username for 'https://github.com': peninonwilliam
Password for 'https://peninonwilliam@github.com': 
remote: Permission to netgen/TagsBundle.git denied to peninonwilliam.
fatal: unable to access 'https://github.com/netgen/TagsBundle.git/': The requested URL returned error: 403`

**Comment by emodric** [comment]
You need to fork the project (button at the top of the page to the right) to your github account and then push the code there. After that, GitHub will give you the option to create a pull request.

Search the github docs for forks and pull requests if you still have problems :)

**Comment by peninonwilliam** [comment]
Thanks for the information, I'll do that
