### ISSUE TITLE
v4.0.0-beta2 - explode() expects parameter 2 to be string, null given

### ISSUE THREAD

**Issue by h-behme** [netgen/TagsBundle#111]
In eZ Platform 3.0.0-beta3 and tagsbundle v4.0.0-beta2, everytime an object with eztags is published and the tags aren't filled, it runs in an error. 
The eztags field isn't required, so it should be fine if it not filled. If it is filled with a tag, everything works fine and the object is published without an error.

Steps to reproduce:

1. Create Content Type with min. one eztags field, field is not required.
2. Create object, fill everything that is required (e.g. the name). Don't add a tag to the eztags field.
3. Publish the Object.

Expected behaviour: Object publishes without any problems.

Actual behaviour: Error Page with message: "explode() expects parameter 2 to be string, null given [in vendor/netgen/tagsbundle/bundle/Form/Type/FieldType/FieldValueTransformer.php:65]" is shown.

(Tested on a fresh eZ Platform 3.0.0-beta3 instance with fresh installed tags bundle)

If you need further information, feel free to ask :)

**Comment by emodric** [comment]
Hi!

Thanks for the error report!

Can you please check if https://github.com/netgen/TagsBundle/pull/106 fixes your problem?

**Comment by h-behme** [comment]
Yes, checked out master and it seems to fix this.
Thank you!

**Comment by emodric** [comment]
Alright, give me an hour to get to the office!

**Comment by emodric** [comment]
@h-behme Tagged 4.0.0-beta3 :)
