### ISSUE TITLE
If using postgres autocomplete is case sensitive

### ISSUE THREAD

**Issue by wizhippo** [netgen/TagsBundle#118]
As like in postgres is case sensitive the causes results to not be returned.

https://github.com/netgen/TagsBundle/blob/f3162ea6814df09cb007b4aea75f842d7436a775/bundle/Core/Persistence/Legacy/Tags/Gateway/DoctrineDatabase.php#L308

perhaps convert to all upper or lower case for the like expression?

**Comment by emodric** [comment]
Hi!

I've pushed to `3.4-release` a fix. Mind testing if everything is okay before tagging?

**Comment by wizhippo** [comment]
@emodric Working thanks

**Comment by emodric** [comment]
Thanks!

Released: https://github.com/netgen/TagsBundle/releases/tag/3.4.6
