### ISSUE TITLE
Missing browser validation for required field

### ISSUE THREAD

**Issue by hgiesenow** [netgen/TagsBundle#123]
Using eztags in eZ 2.5 with the page builder (enterprise edition). I tried to create a page, that contains a ezlandingpage layout as well an eztags field that is required. When i press the "Publish" button, but no tag is selected, the page is being reloaded and all blocks are gone and i'm being asked to select a layout again.
When other required fields are not set, the publish button will not submit the request to the backend and an error message is shown. I would expect the same for the eztags field.

**Comment by emodric** [comment]
Hi!

I cannot reproduce sadly since I don't use enterprise edition with ezlandingpage.

PR is welcome to fix this issue, however :)

**Comment by emodric** [comment]
Released as https://github.com/netgen/TagsBundle/releases/tag/3.4.7 & https://github.com/netgen/TagsBundle/releases/tag/4.0.4
