### ISSUE TITLE
Browse tag input outside of field wrapper

### ISSUE THREAD

**Issue by ludwig031** [netgen/TagsBundle#130]
Browse tag input field falls out of field wrapper in Ibexa administration (3.2)
![image](https://user-images.githubusercontent.com/30387773/109622909-eb3f9900-7b3c-11eb-9b92-3b4f2a2dc098.png)

**Comment by thiagocamposviana** [comment]
It can be solved with this:

` .ez-content-edit .ez-field-edit.ez-field-edit--eztags:after{clear: both; content: ' ';display: block;}`

**Comment by emodric** [comment]
@thiagocamposviana Wanna make a PR? :)

**Comment by thiagocamposviana** [comment]
@emodric Thanks, but the change should be so small it is better you fix it without all the back and forth.

**Comment by emodric** [comment]
Fixed in 4.0.12
