### ISSUE TITLE
Change word separator char in url from + to %20 for Ibexa DXP 3.3.12

### ISSUE THREAD

**Issue by kh09211** [netgen/TagsBundle#144]
Hello, we have recently encountered a situation when upgrading to Ibexa 3.3.12 where it appears that Ibexa has changed from using %20 in it's URL to plus signs. We were not sure the best way to rectify this, so we made a patch to the netgen tag router, and installed it with composer patches package. This works, but is there  a better way?

```
--- tagsbundle/bundle/Routing/TagRouterOriginal.php	2021-12-07 22:40:32.996776616 +0000
+++ tagsbundle/bundle/Routing/TagRouter.php	2021-12-07 22:40:53.085558199 +0000
@@ -85,7 +85,7 @@
         }
 
         $requestedPath = $this->removePathPrefix($requestedPath, $pathPrefix);
-        $requestedPath = trim($requestedPath, '/');
+        $requestedPath = trim(str_replace('+', ' ', $requestedPath), '/');
 
         if ($requestedPath === '') {
             throw new ResourceNotFoundException('Route not found');
```

**Comment by emodric** [comment]
Well, not really. You either do it as you did, or replace the `TagRouter` class completely with a compiler pass.

**Comment by kh09211** [comment]
Thank you Emodric for the reply!
