### ISSUE TITLE
Issue with upgrade from symfony 5.3 to symfony 5.4

### ISSUE THREAD

**Issue by yoyolepsy** [netgen/TagsBundle#146]
Hello,

After installation of Ibexa Experience 3.3.13, I had issue when I tried to create tag from backoffice.
I have this following error "An error has occurred resolving the options of the form "Netgen\TagsBundle\Form\Type\TagTreeType": The option "constraints" with value null is expected to be of type "Symfony\Component\Validator\Constraint" or "Symfony\Component\Validator\Constraint[]", but is of type "null". Nevertheless, when I create a content with tag field, I can create a tag from content edit mode. Moreover, when I click on tag which is not use for a content, I have the following error : "L'argument '$criterion->target' est invalide : No searchable fields found for the given criterion target".

I tried several clean installations : 

- ibexa experience : 3.3.10, netgen/tagsbundle : 4,0.15 , symfo 5.3.9 : ok
- ibexa experience : 3.3.11, netgen/tagsbundle : 4.0.15,  symfo 5.3.10 : ok
- ibexa experience : 3.3.12, netgen/tagsbundle : 4.0.15,  symfo 5.3.10 : ok
- ibexa experience :3.3.13,  netgen/tagsbundle : 4.0.15,  symfo 5.4.2  : ko

It seems there has been some changes on Symfony side that are not reflected in Netgen Tags bundle

**Comment by kh09211** [comment]
Hello, we have also experienced the same issue as Yoyolepsy when upgrading our existing project to Ibexa experience 3.3.14

**Comment by bcafuk** [comment]
Hello, @yoyolepsy 

We have found a solution to the first issue with the constraints. However, we have not been able to reproduce the second issue with the searchable fields.

Could you please provide more detailed steps which lead to this error?
> "L'argument '$criterion->target' est invalide : No searchable fields found for the given criterion target"

**Comment by yoyolepsy** [comment]
Hello, @bcafuk ,

Thanks for the solution. I modified locally waiting a tag will be create. It's works. For the second issue, I can't  longer reproduce it now. Maybe this issue was linked to the first and data have been corrupted. 
So it is ok for me. Thanks again. 

Hello @emodric , I have seen fix has been merged in master, do you know if a tag version will be created soon? 
Thanks in advance

**Comment by emodric** [comment]
@yoyolepsy Yes, I will tag it soon, I was waiting for your feedback regarding the second issue :)

**Comment by yoyolepsy** [comment]
Thanks @emodric .
Thanks again @bcafuk

**Comment by emodric** [comment]
Fixed in 4.0.17.
