### ISSUE TITLE
Urlencode and urldecode

### ISSUE THREAD

**Issue by AUDUL** [netgen/TagsBundle#148]
Tag url is encoded with "urlencode" function but decoded with "rawurldecode"
- https://github.com/netgen/TagsBundle/blob/76fc5230d0c9003a2d541dd460248e1cae1d6b62/bundle/Routing/Generator/TagUrlGenerator.php#L90
- https://github.com/netgen/TagsBundle/blob/76fc5230d0c9003a2d541dd460248e1cae1d6b62/bundle/Routing/TagRouter.php#L65

So I get a 404 error when accessing the tag

Is it possible to choose a single RFC to encode and decode the url

**Comment by AUDUL** [comment]
If you replace the + by %20 the url work

https://www.code-rhapsodie.fr/tags/Technos/Dataflow/eZ+Dataflow

**Comment by patrickallaert** [comment]
I confirm I am facing the same issue.
With tags containing a space, the URL generated by template: `vendor/netgen/tagsbundle/bundle/Resources/views/eztags_content_field.html.twig` for tag "Sport et loisirs" will be:
https://example.com/tags/view/Sport+et+loisirs
Navigating to that page will result in an error: `Could not find 'tag' with identifier 'Sport+et+loisirs'`
However changing the URL to https://example.com/tags/view/Sport%20et%20loisirs works.

**Comment by patrickallaert** [comment]
I can confirm that patch https://gist.github.com/patrickallaert/eb497baef9e3cca4806f8294da6dadaa does solve the problem here.

**Comment by patrickallaert** [comment]
ping @emodric

**Comment by emodric** [comment]
Hi @patrickallaert 

I'll try to take a look at this next week.

Thanks for the proposed solution 👍

**Comment by emodric** [comment]
Fixed in 4.0.18 and 5.0.1.

Thanks @patrickallaert for the fix and @AUDUL for reporting the issue!
