### ISSUE TITLE
Elasticsearch support

### ISSUE THREAD

**Issue by haakonhorvei** [netgen/TagsBundle#150]
Hello! 

Elasticsearch was added as an option for the ([search](https://doc.ibexa.co/en/3.3/guide/search/search/)) in version 3.1. It seems to me like this bundle supports legacy and Solr, but not Elasticsearch. Is there any plans to support Elasticsearch in the future?

**Comment by emodric** [comment]
Hi @haakonhorvei 

Currently, there's no plans to support Elastic search due to implementation in Ibexa being closed source.
