### ISSUE TITLE
Tag new version?

### ISSUE THREAD

**Issue by torjusb** [netgen/TagsBundle#17]
Would it be possible to tag a new version with the changes in the master branch? I need to get the "subTreeLimit" option which only seems to be available with the changes in the master branch. I'd prefer to avoid having to rely on using "dev-master" in Composer.

Thanks!

**Comment by emodric** [comment]
Hey @nifty 

I can do that, but give me a day or two to check it out, I need to sync the tagging with legacy eztags extension, since they're dependent.

**Comment by emodric** [comment]
Hi @torjusb!

I know this was long overdue and sorry for that, but now the new tag is finally created :)
