### ISSUE TITLE
eztags bundle causing fatal error in ezpublish enterprise 5.4.2

### ISSUE THREAD

**Issue by markblackmore** [netgen/TagsBundle#22]
Hi 
I upgraded from enterprise version 5.4.1 to 5.4.2 and now get this fatal error:
`The parent definition "ezpublish.persistence.legacy.search.gateway.criterion_handler.base" defined for definition "ezpublish.persistence.legacy.search.gateway.criterion_handler.common.tag_id" does not exist.`
I can see that in vendor/netgen/tagsbundle/Netgen/TagsBundle/Resources/config/storage_engines/legacy/search_query_handlers.yml ezpublish.persistence.legacy.search.gateway.criterion_handler.base is referenced and this service is now removed in ezpublish-kernel: https://github.com/ezsystems/ezpublish-kernel/commit/212f53c5936b21aba9be0c3f3abd52d7a5d99488
This also relates to https://jira.ez.no/browse/EZP-23940

**Comment by emodric** [comment]
Hi @markblackmore 

This is a known issue, please see #19 and #21.

Please use `search_namespace_rename` branch for the time being which fixes the issue. I cannot merge it to master and tag it yet, since eZ Publish Community in latest version (2014.11) still uses the old namespaces.

**Comment by markblackmore** [comment]
OK, thankyou.
