### ISSUE TITLE
Implement eZ\Publish\SPI\FieldType\Indexable

### ISSUE THREAD

**Issue by htollefsen** [netgen/TagsBundle#25]
As talked about in #23 it would be awesome if this bundle would implement ```eZ\Publish\SPI\FieldType\Indexable```! It would be great to use ```Criterion\Field( "fieldtype_identifier", Criterion\Operator::CONTAINS, "MyEzkeyword" )``` to fetch locations based on tags together with other criterions, e.g. in article categories and such.

I really hope you will look into this in the near future!

**Comment by emodric** [comment]
I will implement it, but I'm not yet 100% sure when exactly. I did start looking into it, the way in which search API is implemented as a whole.

**Comment by emodric** [comment]
@htollefsen I've implemented tags indexing handler, as discussed at PHP Summer Camp :)

Test away! :) If you have any suggestions, do tell :)

https://github.com/netgen/TagsBundle/commit/d7515266ac5cbd7904bf11dc46bf03cbe811f53b

**Comment by htollefsen** [comment]
Great! Hopefully I'll find time to check it out within next week

**Comment by emodric** [comment]
Great :)

Also implemented (https://github.com/netgen/TagsBundle/commit/d506406a57150453c2b5f85fc0dff5e009fc710b) are Solr criterion visitors for `TagId` and `TagKeyword` criteria, so you should be able to use those too, in addition to `Field` criterion.

**Comment by htollefsen** [comment]
Awesome!

**Comment by emodric** [comment]
@htollefsen Did you test indexing of `eztags` field type? I will release 2.1.0 today and if something is broken, the fix will need to be in a patch release :)

**Comment by jxn** [comment]
@emodric I've tested this today successfully.  I believe you should be able to close this ticket.

**Comment by emodric** [comment]
@jxn Thanks! Closing!
