### ISSUE TITLE
Get tags that start with a value via tagservice

### ISSUE THREAD

**Issue by wizhippo** [netgen/TagsBundle#27]
To create an auto-complete function for keywords the ability is needed to get tags with a keyword starting with a value.  Should this be added to the tagservice?  Should it be an extension to getTagsByKeyword or a new getTagsByKeywordStartingWith or similar function?

**Comment by emodric** [comment]
That's a good idea @wizhippo!

I'll think about the best approach for implementing this.

**Comment by volarname** [comment]
any progress on this?

**Comment by emodric** [comment]
@volarname It stalled a bit, yes, but this will need to be implemented soon in some form or the other to facilitate autocomplete in new field edit interface for Platform UI.

**Comment by emodric** [comment]
Implemented in master branch and version 3.0, soon to be released :)
