### ISSUE TITLE
Incompatibility with ezpublish-kernel 6.0.0-alpha2

### ISSUE THREAD

**Issue by edgecrusherr** [netgen/TagsBundle#28]
The bundle seems to be incompatible with the mentioned version: 

 Fatal error: Declaration of Netgen\TagsBundle\Core\Search\Legacy\Content\Common\Gateway\CriterionHandler\TagId::handle() must be compatible with eZ\Publish\Core\Search\Legacy\Content\Common\Gateway\CriterionHandler::handle

Is there a quick fix for this? Thanks

**Comment by edgecrusherr** [comment]
Just noticed the pull request, apologies for the duplicate issue. Has there been any news on the coming version?

**Comment by emodric** [comment]
I cannot tag it yet unfortunatelly. It would break eZ Publish Enterprise 5.4.2. This API is different in 5.4.1, 5.4.2 and eZ Platform and it's not easy keeping compatibility between minor versions, yet alone different products altogether.

The best I could do perhaps is to patch the master branch but without tagging.
