### ISSUE TITLE
eZ Platform support

### ISSUE THREAD

**Issue by nmeirik** [netgen/TagsBundle#33]
Is this compatible with the upcoming release of eZ Platform? When I install it I get the error

`PHP Fatal error:  Interface 'eZ\Bundle\EzPublishLegacyBundle\LegacyBundles\LegacyBundleInterface' not found in /var/www/vendor/netgen/tagsbundle/Netgen/TagsBundle/NetgenTagsBundle.php on line 9`

**Comment by emodric** [comment]
Yes it is, but still requires legacy. I will make sure that it's optional though.

Thanks for reporting it!

**Comment by emodric** [comment]
@nmeirik I've removed the interface in question from bundle class as well as hard requirement for `ezsystems/eztags-ls` in `composer.json`. Please note that only 2.1 (`dev-master` for now) will have this removed. 2.0.x versions will remain compatible with eZ 5.
