### ISSUE TITLE
Parent definition does not exist

### ISSUE THREAD

**Issue by DeClemo** [netgen/TagsBundle#34]
Hi Guys,

I've just upgraded to eZ 5.4.5 and I'm getting the below error when trying to load the page now. I'm not sure why it has cropped up now as I can see the configuration in the yml files in the core eZ Publish settings folder but for some reason it doesn't seem to exist.

```
  [Symfony\Component\DependencyInjection\Exception\RuntimeException]                                                                                                                       
  The parent definition "ezpublish.search.legacy.gateway.criterion_handler.base" defined for definition "ezpublish.search.legacy.gateway.criterion_handler.common.tag_id" does not exist.
```

Could you give me an idea of what to look at to get this fixed?

Thanks,
Dan

**Comment by htollefsen** [comment]
@DeClemo If I'm not mistaken `ezpublish.search.legacy.gateway.criterion_handler.base` has been replaced with `ezpublish.search.legacy.gateway.criterion_handler.content` and `ezpublish.search.legacy.gateway.criterion_handler.location`.

**Comment by emodric** [comment]
@htollefsen is right. I'm not sure in which Enterprise version this occured though.

@DeClemo Which version of Tags bundle are you using? Did you try upgrading to latest 1.x (I presume you're still on 1.x)?

**Comment by DeClemo** [comment]
@htollefsen according to changes-5.4.md ezpublish.search.legacy.gateway.criterion_handler.content is the tag but ezpublish.search.legacy.gateway.criterion_handler.base is still defined in criterion_handlers_common.yml

@emodric I am running latest 1.x version of the tags bundle.

I have managed to get things going now by copying the service definition from criterion_handlers_common.yml into my site bundle. Not quite sure why it's not being read out of the core settings bundle anymore though. It was working fine with 5.4.2 version of the kernel.

Thanks for the help guys. Much appreciated.

**Comment by emodric** [comment]
@DeClemo I'm glad you fixed it. If you found out why it wasn't working in the first place, let me know. I'm not using Enterprise so it's hard for me to check.

**Comment by DeClemo** [comment]
@emodric Will do! :-)

**Comment by nicogommen** [comment]
Hi,
I've just upgraded to eZ 5.4.5 (from 5.4.4) and I got the same error as @DeClemo.
`[Symfony\Component\DependencyInjection\Exception\RuntimeException]                                                                                                                       
  The parent definition "ezpublish.search.legacy.gateway.criterion_handler.base" defined for definition "ezpublish.search.legacy.gateway.criterion_handler.common.tag_id" does not exist.`

I did tried to copy the service definition from criterion_handlers_common.yml into my site bundle as @DeClemo did, but now I have another error:
`[Symfony\Component\Debug\Exception\FatalErrorException]
Compile Error: Declaration of Netgen\TagsBundle\Core\Limitation\TagLimitationType::evaluate() must be compatible with eZ\Publish\SPI\Limitation\Type::evaluate(eZ\Publish\API\Repository\Values\User\Limitation $value, eZ\Publish\API\Re  
  pository\Values\User\UserReference $currentUser, eZ\Publish\API\Repository\Values\ValueObject $object, array $targets = NULL)`

After the upgrade, here are the version of the packages we are using:
ezsystems/comments-bundle                    v5.4.2    
ezsystems/demobundle                         v5.4.4    
ezsystems/ezautosave-ls                      v5.4.2    
ezsystems/ezdemo-ls-extension                v5.4.2    
ezsystems/ezflow-ls-extension                v5.3.8    
ezsystems/ezgmaplocation-ls-extension        v5.3.1    
ezsystems/ezie-ls                            v5.3.1    
ezsystems/ezmbpaex-ls                        v5.3.2    
ezsystems/ezmultiupload-ls                   v5.3.0    
ezsystems/ezodf-ls                           v5.3.1    
ezsystems/ezprestapiprovider-ls              v5.3.0    
ezsystems/ezpublish-kernel                   v5.4.5    
ezsystems/ezpublish-legacy                   v5.4.5    
ezsystems/ezpublish-legacy-installer         v2.0.1    
ezsystems/ezscriptmonitor-ls                 v5.3.1    
ezsystems/ezsi-ls                            v5.3.3    
ezsystems/ezstarrating-ls-extension          v5.3.1    
ezsystems/eztags-ls                          1.4.2     
ezsystems/ezwt-ls-extension                  v5.3.5    
ezsystems/ngsymfonytools-bundle              v1.0.5    
ezsystems/recommendation-bundle              v1.0.0-rc2
friendsofsymfony/http-cache                  1.4.2     
friendsofsymfony/http-cache-bundle           1.3.6     
friendsofsymfony/jsrouting-bundle            1.5.4     
netgen/tagsbundle                            1.2.5

Thanks,
Nico

**Comment by emodric** [comment]
Hi @nicogommen,

Concerting the first issue, I really can't see why it would happen. Moreover, when I install 5.4.5, everything works fine. I can't see anything wrong it, really. Legacy search engine bundle is active (maybe this is the issue with you?), and it loads the file where `ezpublish.search.legacy.gateway.criterion_handler.base` is defined so it should just work, and by default it does :)

Concerning the second problem, the fix is available in tags bundle 2.0.x only (https://github.com/netgen/TagsBundle/commit/f7f69ebcf603e763ffc8181ee085f09fcd95fe1b).

The problem with this specific patch is that eZ Systems decided to make breaking changes in their APIs in patch releases, which makes it difficult for bundle developers to track and adopt to, especially since you have 4(!) versions of product active: eZ Community 2014.11, eZ Enterprise 5.4.x (with every patch release further breaking something), eZ Platform and eZ Studio.

If there is interest (if you don't plan to upgrade to 2.0.x, that is), I can try and make a patch is 1.2.x branch to fix `UserReference` issue (or you could make a PR against 1.2 branch ;))

**Comment by Plopix** [comment]
Yo,
I ran into the same issue.

I remove the eZ Tags service to do a container debug:

```
php ezpublish/console container:debug | grep ezpublish.search
  ezpublish.search.common.field_name_generator                                             eZ\Publish\Core\Search\Common\FieldNameGenerator
  ezpublish.search.common.field_name_resolver                                              eZ\Publish\Core\Search\Common\FieldNameResolver
  ezpublish.search.common.field_registry                                                   eZ\Publish\Core\Search\Common\FieldRegistry
  ezpublish.search.slot.copy_content                                                       eZ\Publish\Core\Search\Common\Slot\CopyContent
  ezpublish.search.slot.copy_subtree                                                       eZ\Publish\Core\Search\Common\Slot\CopySubtree
  ezpublish.search.slot.create_location                                                    eZ\Publish\Core\Search\Common\Slot\CreateLocation
  ezpublish.search.slot.create_user                                                        eZ\Publish\Core\Search\Common\Slot\CreateUser
  ezpublish.search.slot.create_user_group                                                  eZ\Publish\Core\Search\Common\Slot\CreateUserGroup
  ezpublish.search.slot.delete_content                                                     eZ\Publish\Core\Search\Common\Slot\DeleteContent
  ezpublish.search.slot.delete_location                                                    eZ\Publish\Core\Search\Common\Slot\DeleteLocation
  ezpublish.search.slot.delete_version                                                     eZ\Publish\Core\Search\Common\Slot\DeleteVersion
  ezpublish.search.slot.hide_location                                                      eZ\Publish\Core\Search\Common\Slot\HideLocation
  ezpublish.search.slot.move_subtree                                                       eZ\Publish\Core\Search\Common\Slot\MoveSubtree
  ezpublish.search.slot.move_user_group                                                    eZ\Publish\Core\Search\Common\Slot\MoveUserGroup
  ezpublish.search.slot.publish_version                                                    eZ\Publish\Core\Search\Common\Slot\PublishVersion
  ezpublish.search.slot.recover                                                            eZ\Publish\Core\Search\Common\Slot\Recover
  ezpublish.search.slot.set_content_state                                                  eZ\Publish\Core\Search\Common\Slot\SetContentState
  ezpublish.search.slot.trash                                                              eZ\Publish\Core\Search\Common\Slot\Trash
  ezpublish.search.slot.unhide_location                                                    eZ\Publish\Core\Search\Common\Slot\UnhideLocation
```

That means some services are not loaded. Then go back to the documentation ;-)

```
From 5.4.4 or lower
Enable the LegacySearchEngineBundle in the kernel
Edit ezpublish/EzPublishKernel.php, and instantiate eZ\Bundle\EzPublishLegacySearchEngineBundle\EzPublishLegacySearchEngineBundle in the list of enabled bundles in the $bundles array in the registerBundles() method, right before EzPublishLegacyBundle.
```

And now everything is loaded.

**Comment by emodric** [comment]
@Plopix Thanks for testing! Care to make a pull request to install docs? :)

**Comment by emodric** [comment]
@DeClemo @htollefsen @nicogommen @Plopix I've added a note in install instructions about need to activate legacy search engine bundle. https://github.com/netgen/TagsBundle/commit/c6780dff4cec12a46bbb7d85ffb8c0a97d14d8e4

I've also made sure that in newer versions things don't crash if bundles don't exist: https://github.com/netgen/TagsBundle/commit/114c5df8ae3a1986eaf943de4923779ed4a893e4

**Comment by emodric** [comment]
Thanks everyone for reports, I know it took a while to find the real cause :+1:
