### ISSUE TITLE
Question: Tag management in v. 2.1

### ISSUE THREAD

**Issue by nmeirik** [netgen/TagsBundle#35]
I'm not totally clear on what to expect from v. 2.1 which requires eZ Platform 1.0.

Should one be able to edit which tags are associated with an object from the new PlatformUI in this version, or does it simply provide services for extracting existing tag relations which can still only be managed in the legacy admin UI?

**Comment by emodric** [comment]
Hi @nmeirik.

2.1 still needs legacy to edit the tags through the admin interface, yes. Platform UI support is planned of course. ( and PRs are accepted too :) )

**Comment by nmeirik** [comment]
Thanks for clearing that up!
