### ISSUE TITLE
Input not showing in eZ Platform with eZ Studio 1.4

### ISSUE THREAD

**Issue by alexmartinsbr** [netgen/TagsBundle#40]
We installed this bundle into our eZ Platform with eZ Studio 1.4 but the input didn't render.
Seams like YUI module is calling JQuery functions, but DOM elements are not there yet.

Can you guys give us some tips?

**Comment by emodric** [comment]
Hi!

Sorry, Platform UI interface is not ready yet. The files are there, yes, but not functional at the moment.

**Comment by emodric** [comment]
You will need to use legacy for the time being if you want admin UI for tags.

I realize this is suboptimal, but currently we don't have the manpower to implement this since it's quite a big and non trivial task.

**Comment by emodric** [comment]
Implemented in master branch and version 3.0, soon to be released :)
