### ISSUE TITLE
TagsBundle 2.0 is not compatible with eZPublish 2014.11

### ISSUE THREAD

**Issue by gggeek** [netgen/TagsBundle#41]
The composer.json of the Tags Bundle makes you think that it is compatible, but when you try to use, you get the following error:

```The parent definition "ezpublish.search.legacy.gateway.criterion_handler.base" defined for definition "ezpublish.search.legacy.gateway.criterion_handler.common.tag_id" does not exist```

That parent service indeed seems to be present in 5.4, but not in 2014.11...

**Comment by emodric** [comment]
Hi @gggeek ! 

Are you sure about this? I'm running latest version of the bundle with Netgen variant of 2014.11 without any issues.

It's not the real 2014.11, sure, but Netgen variant doesn't have any breaking changes so it should not matter.

**Comment by gggeek** [comment]
Well that service in 5.4 is defined in ...Core/settings/search_engines/legacy/criterion_handlers_common.yml

That file is definitely not there in 2014.11

It might be possible that just adding a definition for the service will do the trick - but if so, it has to be documented

**Comment by emodric** [comment]
Okay about the file, but is it defined somewhere else in the kernel?

As I said, I'm running it on Netgen variant of 2014.11 and it's working fine.

Did you try the latest 2.0.x available?

**Comment by gggeek** [comment]
I grepped thru the kernel, and could not find it anywhere else... Maybe you have added the solr-search-bundle to that project?

**Comment by emodric** [comment]
This is the code that decides which search handlers will the bundle load, ones for 2014.11, or ones for 5.4 and later: https://github.com/netgen/TagsBundle/blob/2.0-release/DependencyInjection/NetgenTagsExtension.php#L35-L39

Can you check if you have that parameter defined in your container and why not if it's not present?

**Comment by gggeek** [comment]
Indeed that parameter does exist in that file...
Either that file is not loaded at the time that the Extension class executes, or there is some other snag somewhere. I will try to step thru execution to find the root cause

**Comment by gggeek** [comment]
Btw, here is the log of the filing build. It's all automated, and starts off with installing ezcommunity 2014.11 and tagsbundle 2.0.11. Very little customizations of the environment...

https://travis-ci.org/kaliop-uk/ezmigrationbundle/jobs/168624059

**Comment by gggeek** [comment]
ps: at first sight the legacy kernel storage engine config is loaded via the ezp core bundle, which is just an Sf bundle like the others. In my ezpublishkernel.php I load the tagsBundle as 2nd bundle - before the ezp kernel. Maybe I should move its loading to last...

**Comment by emodric** [comment]
@gggeek Any news? Did you manage to get it working?

**Comment by gggeek** [comment]
Yes! :-) https://travis-ci.org/kaliop-uk/ezmigrationbundle/jobs/169059166

So I lower this ticket to 'documentation improvements' :-)

**Comment by emodric** [comment]
Great! Care to make a PR with a note in docs for your fix? :)

**Comment by gggeek** [comment]
https://github.com/netgen/TagsBundle/pull/42

**Comment by gggeek** [comment]
fixed typo
