### ISSUE TITLE
Get Contents by Muliple tags

### ISSUE THREAD

**Issue by longnd** [netgen/TagsBundle#43]
What I am trying to do is creating a function to select multiple tags and filter contains by those tags with pagination.
but it looks like there is no way to get contents my multiple tags

I checked the TagViewController 
https://github.com/netgen/TagsBundle/blob/2.0-release/Controller/TagViewController.php#L46
There is a function to render contents by a particular tag with pagination
**viewTag()** which loads the tag by ID then calls the **renderTag()** function to render contents

and also the TagService
https://github.com/netgen/TagsBundle/blob/2.0-release/Core/Repository/TagsService.php
there're several functions to get tag and it's related contents, including: 
**loadTag()**, **loadTagChildren()**, **loadTagsByKeyword()**, **getRelatedContent()**, ...

None of those provide a mechanism to load contents by multiple tags (to paginate)
Is it not supported yet or am I missing some points?

Any clarifications would be highly appreciated.
Thank you

**Comment by emodric** [comment]
Hi @longnd !

You can use `TagId` criterion included in the bundle (https://github.com/netgen/TagsBundle/blob/2.0-release/API/Repository/Values/Content/Query/Criterion/TagId.php) to fetch the content tagged with multiple tags via eZ Publish search service.
