### ISSUE TITLE
Criterion\TagId does not support operators

### ISSUE THREAD

**Issue by phibo23** [netgen/TagsBundle#44]
As far as I understand, both TagId and TagKeyword criteria should support support ez operators EQ and IN. This works fine for TagKeyword but if I try the same with TagId 
```php
new TagId(Criterion\Operator::EQ, $tagId);
```
I get an InvalidArgumentExeption with the message 
```
Argument '$criterion->target' is invalid: No searchable fields found for the given criterion target '590'.
```

looking into your tests I found a working syntax without operator https://github.com/netgen/TagsBundle/blob/master/Tests/Core/Search/Solr/Query/Content/CriterionVisitor/Tags/TagIdTest.php#L52
```php
new TagId($tagId);
```
but is this how it is supposed to work given this specification? https://github.com/netgen/TagsBundle/blob/master/API/Repository/Values/Content/Query/Criterion/TagId.php#L33

**Comment by emodric** [comment]
Hi!

Specification only signals to the implementations of the search engine what it supports. It doesn't mean that you need to transfer the operator in the criterion. What you pass to the criterion depends purely on the criterion constructor.

`TagId` criterion internally transfers the operator automatically, based on the input, I believe.

**Comment by emodric** [comment]
On further inspection, you can also use `new TagId(array(1, 2, 3))` to get the content having any of those tag IDs. The difference  wtih `TagKeyword` comes from `TagKeyword` having an additional operator, so we needed the operator explicitly.

Unfortunatelly, now it's probably too late to change the signature of the criterion constructor as it would be a pretty big breaking change, even for the next major version.

**Comment by phibo23** [comment]
ok, as I said, I already found the working syntax. But I still find it strange to have different constructors for criteria which are meant to be used more or less in the same way. ;)

**Comment by emodric** [comment]
Yes, I know, but that is the result of those criterions not being developed at the same time. At first, there was only `TagId` criterion which was designed after `LocationId` criterion from eZ kernel, which works in the same way, and `TagKeyword` criterion was introduced at a later time when it was already too late for changing things.
