### ISSUE TITLE
NotFoundException when using /tags/view with a synonym

### ISSUE THREAD

**Issue by supasteev0** [netgen/TagsBundle#51]
Trying to view all content related to a synonym via the /tags/view route, I get a NotFoundException.

It seems the issue may come from the getFullTagDataByKeywordAndParentId method in vendor/netgen/tagsbundle/Netgen/TagsBundle/Core/Persistence/Legacy/Tags/Gateway/DoctrineDatabase.php.

Indeed, in the eztags database table, synonym has a value in main-tag-id field, corresponding to its main tag. But in the doctrine query in the getFullTagDataByKeywordAndParentId, the main_tag_id value is always 0.

**Comment by emodric** [comment]
Fixed in [`2.2.4`](https://github.com/netgen/TagsBundle/releases/tag/2.2.4)

Thanks @supasteev0 !
