### ISSUE TITLE
Long tag name handling

### ISSUE THREAD

**Issue by brendan-pike** [netgen/TagsBundle#52]
In the tags/admin/ interface long tag names extend beyond the left column.  On one site I use this for creating content filters on certain government standards. The longest for example is "2.4 Understand and respect Aboriginal and Torres Strait Islander people to promote reconciliation between Indigenous and non-Indigenous Australians" which is a couple levels down.  This makes the line around 1000px wide. In this situation the left menu needs either wrapping, abbreviating and/or for the left column to be resizable.

**Comment by emodric** [comment]
Hey @brendan-pike!

Thanks for the report, @goranNetgen is on it. We decided it would be best to both wrap the long names as well as allow the user to resize the tree column.

**Comment by emodric** [comment]
Fixed in c90528340127cd6f14168336d354f2f7d6a0efce
