### ISSUE TITLE
Tags for site limited by siteaccess

### ISSUE THREAD

**Issue by Mrkisha** [netgen/TagsBundle#55]
Is it possible to have tags that are siteaccess aware or at least language aware?

**Comment by emodric** [comment]
Hi!

I'm not sure what you mean exactly. Tags can have as many translations as you wish. Is that what you're looking for?

**Comment by Mrkisha** [comment]
What I mean is, I have multiaccess website. If I create a tag from domain1 in language1, I dont want to see it in search as you type drop-down in domain2 with language2. Does it make sense?

**Comment by emodric** [comment]
Well, that depends on your siteaccess settings and their languages.

Tags Bundle follows the languages configuration specified there, just as content objects.

**Comment by Mrkisha** [comment]
Language1 cant be used in domain2. Yet I get to see all the tags (no matter what the language or siteaccess is). Am I missing something with permissions?

**Comment by emodric** [comment]
Can you paste here your usage example which returns tags that are not supposed to be used?

**Comment by Mrkisha** [comment]
I have tag field in Article content type.

There are 2 siteaccesses, `siteaccess1` with `language1` and `siteaccess2` with `language2`. 
If I access back-end of eZ Platform from `siteaccess1` and create one tag with value `testtag` for `language1`.
Then I access back-end of the `siteaccess2` and create Article content type and go to tag field, once I start typing `tes`, I get tag from `siteaccess1` of the `language1`. 

I wonder if the tags are siteaccessaware and languageaware, or there is a tag permission setup on user I should apply in order to achieve two aware states?

**Comment by emodric** [comment]
Are your tags always available?

If tags are always available, they will show up in the list with their main language, even if they don't have the required translation.

In the below screenshot, "Use the main language if there is no prioritized translation" should be UNCHECKED for your tags.

![image](https://cloud.githubusercontent.com/assets/362286/25653456/3907aafa-2fed-11e7-9499-070807e89c01.png)

**Comment by Mrkisha** [comment]
Already tried it. It does not work. 
I still get in the dropdown all the tags that match, despite the language.

**Comment by emodric** [comment]
Then this is indeed a bug :)

Search should not return tags which are not always available.

**Comment by emodric** [comment]
@Mrkisha This should be fixed with the following patch: https://github.com/netgen/TagsBundle/commit/9ba7f2bf601204a52b16cefcb5ba38fd04fc3bb2

Can you test and report back if it is working for you, so I can tag it?

**Comment by Mrkisha** [comment]
@emodric  on it.

**Comment by Mrkisha** [comment]
@emodric I'm still getting tags from other languages.

**Comment by emodric** [comment]
@Mrkisha Are you sure? With the patch I commited, it is working for me as expected.

For example:

My siteaccess where Platform UI is running is configured to show English and Croatian.
I added a tag in German.
I disabled "Always available" flag on the tag
Tag is not shown in the dropdown when I search for it in the field.
Once I enable "Always available" flag, tag is then shown when searching for it.

**Comment by Mrkisha** [comment]
The previous try was with 3.0.2 tag.
However I've tried with 9ba7f2b patch and now I dont see Tags menu item, while in System Info says that Tags bundle is installed.
![image](https://cloud.githubusercontent.com/assets/1561303/25850402/6a5f6cbc-34c2-11e7-9898-f645d5d0e2d3.png)

**Comment by emodric** [comment]
Hi! https://github.com/netgen/TagsBundle/commit/9ba7f2bf601204a52b16cefcb5ba38fd04fc3bb2 is actually in `2.2-release` branch, which was merged into `3.0-release`, so you should actually use https://github.com/netgen/TagsBundle/commit/52490d817a31e9baad133d98085445664537db5f

**Comment by Mrkisha** [comment]
Ok, now works!

I would be great if it was siteaware as well. As I have two different siteaccess with some language.

**Comment by emodric** [comment]
@Mrkisha Great, thanks for testing! So I can tag `3.0.3` with the fix?

About siteaccess awareness, yeah, I know it would be nice. But, since there's no official site API yet for eZ Platform, I'd rather not reinvent the wheel, so maybe a future release will have it. I'll keep #56 open to remind me :)

I hope that is okay :)

**Comment by Mrkisha** [comment]
Go ahead and merge.

**Comment by emodric** [comment]
Fixed in versions 2.2.5 and 3.0.3
