### ISSUE TITLE
PHP 7.1 requirement is inconvenient ;-)

### ISSUE THREAD

**Issue by sandrinr** [netgen/TagsBundle#67]
We are running the TagsBundle 3.1.4 with PHP 7.0 without issues. Our guess is that "dropping support for PHP 7.0" was done out of principle. However, since for example Ubuntu 16.04 is shipping PHP 7.0 by default and will be supported (including PHP) for a long time, it is inconvenient to have to stick to the TagsBundle 3.0.x for the at the moment.

Any chance for that requirement to be relaxed again?

**Comment by emodric** [comment]
Hi,

you should not use PHP 7.0 any more since recently active support ended for it. Ubuntu shipping and maintaining PHP 7.0 for the next couple of years is an antipattern, rather than a positive thing: https://paragonie.com/blog/2017/12/2018-guide-building-secure-php-software#php-versions

Having said that, I can relax the restriction in 3.1 if you find that helpful, but not for any further versions.

**Comment by sandrinr** [comment]
Hi @emodric , thank you for your response.
> you should not use PHP 7.0 any more since recently active support ended for it. Ubuntu shipping and maintaining PHP 7.0 for the next couple of years is an antipattern, rather than a positive thing: https://paragonie.com/blog/2017/12/2018-guide-building-secure-php-software#php-versions

Trying to educate your users through means of composer requirement specifications is not something we would have opted for. We specify our requirements strictly out of the technical needs of the packages in question and try to keep them as relaxed as possible. We are under the impression that this is common practice in the Symfony world. However, this is your package and therefore you do that however you seem fit :-).

> Having said that, I can relax the restriction in 3.1 if you find that helpful, but not for any further versions.

That you are able to relax the restriction is obvious but if you do not feel comfortable to do so then please, by all means, keep it as it is. We can always just use `--ignore-platform-reqs`when updating the `netget/tagsbundle` or even fork it should that become necessary.

Best regards and again thanks for the consideration!

**Comment by emodric** [comment]
> That you are able to relax the restriction is obvious but if you do not feel comfortable to do so then please, by all means, keep it as it is.

As I said, I am willing to relax the restriction to PHP 7.0 for Tags Bundle 3.1, but I am definitely not planning to support PHP 7.0 later on.

The reason why I dropped it now is to possibly have easier migration later on when I drop support for PHP 5 and add scalar type hints and so on. Going from PHP 5 to PHP 7 is fine for major version, but requiring bump from PHP 7.0 to PHP 7.1 might be seen as inconvenient. So my intention was to limit to PHP 7.1 now, so later on I can use PHP 7.1 syntax without thinking if there are people using PHP 7.0.

I'll leave the decision to you. If you want it relaxed, I can do it for now, but it will be only a temporary measure.
