### ISSUE TITLE
eZPublish SPI cache not cleared when renaming a tag

### ISSUE THREAD

**Issue by gggeek** [netgen/TagsBundle#75]
Tested when editing tags via eztags extension, but it probably happens when editing tags via tagbundle as well (and even if not, the fix is probably better done in tagsbundle than elsewhere anyway):

- have Article template display the value of a Tag field
- add tag with value XXX to an Article
- access said Article full view
- in Legacy Admin, edit the tag, rename it to XXY
- restart Varnish, in order to avoid any http caching getting in the way
- access said Article full view => you still see tag XXX

This happens because the SPI Cache for the content is not cleared when the tag is edited, and apparently the tag name is stored in it.

Workaround found so far:
1. convert ezpEvent events to Sf slots (those exists already in both eztags ext and eztags bundle)
2. add a slot listener for eztag event "UpdateTagSignal"
3. in it, clear SPi cache for the contents related to the given tag Id (currently needs subclassing eZ\Publish\Core\Persistence\Cache\ContentHandler)

**Comment by emodric** [comment]
@andrerom What do you think? What would be the best way to approach this? Are slots the right place to have SPI caches cleared?

**Comment by andrerom** [comment]
I'm not familiar with what was done in terms of caching here, or if this is v2 or v1 issue.

**Comment by gggeek** [comment]
v1

**Comment by andrerom** [comment]
Ah, but this is editing in legacy, so more of an issue with legacy bridge to handle then.
But I don't think eztags emits any events for legacy bridge to listen to in order to clear the cache.

This is the new cache introduced recently here right? It's possible but would need some work across all repos, across misc versions.

Workaround is to downgrade to TagsBundle 3.2 or lower.

**Comment by gggeek** [comment]
Well, I am not sure if it is "only" legacy related.

The problem does manifest itself when editing in legacy, true.
But the SPI cache is definitely in the eZ5 "layer".

What I have done in project code (waiting to have some time to make a PR out of it) is to
1. have tagsBundle activate its signals upon the ezpevents being fired by eztags extension
2. set up a Slot for the tagsBundle signal which clears the SPI cache

**Comment by emodric** [comment]
Closing as obsolete.
