### ISSUE TITLE
Tree view broken?

### ISSUE THREAD

**Issue by omh** [netgen/TagsBundle#86]
First off, thanks for creating and maintaining this great extension! 

I'm experiencing a problem with the "tree view" on a fresh copy of eZ Platform 2.3.1 with TagsBundle 3.3.2. Just me? "Default view" and "Standard view" appears to work fine.

Error:
```
TypeError: EzTags[builder] is not a constructor[Learn More] c104ca5_jquery.eztags_5.js:1015:18
$.fn[plugin]/<
http://diku.loc/js/c104ca5_jquery.eztags_5.js:1015:18
each
http://diku.loc/js/b22ba31_jquery.min_3.js:2:2571
each
http://diku.loc/js/b22ba31_jquery.min_3.js:2:1238
$.fn[plugin]
http://diku.loc/js/c104ca5_jquery.eztags_5.js:1006:13
<anonymous>
http://diku.loc/js/c104ca5_init_7.js:28:21
<anonymous>
http://diku.loc/js/c104ca5_init_7.js:3:2
```
![screenshot 2018-11-14 at 08 46 54](https://user-images.githubusercontent.com/46762/48467760-2a217780-e7ea-11e8-80b2-0795f43616cb.png)

![screenshot 2018-11-14 at 08 43 05](https://user-images.githubusercontent.com/46762/48467636-c8610d80-e7e9-11e8-8844-7d881bc262a9.png)

**Comment by emodric** [comment]
Hi. Thanks for the bug report. It is indeed an issue, since tree view is not implemented yet, simply haven't had the time to tackle it yet :/

I might disable the option altogether, to avoid these errors until it is implemented.

**Comment by omh** [comment]
Thanks for the quick reply. Yes, I guess just removing the option is a good start to avoid confusion :). I'll close this for now.

**Comment by emodric** [comment]
I've pushed a new `3.3.3` tag which has the option removed.

Thanks once again for the report @omh !
