### ISSUE TITLE
Layout issues when editing an object without tag edit permissions

### ISSUE THREAD

**Issue by omh** [netgen/TagsBundle#87]
Hi,

If you try to create a new object with a tag attribute and the current user does not have edit permissions for tags there's some layout issues. Once a tag is added (or you have edit permissions and the add button is visible) everything is good.

![screenshot 2018-12-12 at 11 43 22](https://user-images.githubusercontent.com/46762/49864740-75d43a80-fe03-11e8-9a55-5e7f410fb094.png)

**Comment by emodric** [comment]
@goranNetgen Can you take a look?

**Comment by omh** [comment]
Note: this issue will be fixed by PR #90

**Comment by emodric** [comment]
Hi @omh ! Is this issue fixed with #95 (which is a successor of #90) ?

**Comment by omh** [comment]
@emodric Yepp, feel free to close this when merged!

**Comment by emodric** [comment]
It is already merged :)

Thanks for clarifying, closing!
