### ISSUE TITLE
Hugh performance issues on heavy Tags usage

### ISSUE THREAD

**Issue by andrerom** [netgen/TagsBundle#92]
It's been observed by several (partners, eZ folks) that Tags bundle does not perform at all due to excessive cache lookups, the issue is most visible on v2 as in-memory cache on v1 tends to hide it. From profiling @bdunogier could see 4 duplicate lookups for tags due to `fromHash()` being implicitly called several times, and this seems to correspond to what @dspe observed during an audit too.

From initial look it seems two things could be done in `fromHash`:
- change to multi lookup of tags to avoid the foreach loading approach
- local caching of values _(for instance property with cached value, checksum of ids looked for, and timestamp to not cache too long on cli operations)_

Or the lookup should rather be done in external storage or something.

Local cache might not be needed once we ship SPI cache with in-memory cache in 2.5, but TagsHandler will need to be adapted for it will most likely be per handler logic.

**Comment by emodric** [comment]
Thanks for the report @andrerom 👍 

If you have suggestions on how to improve, I'll gladly merge them!

**Comment by andrerom** [comment]
Not really as it seems to go deep, but I might be wrong, @bdunogier was the one spotting this so he might know.

**Comment by emodric** [comment]
@andrerom Will this be closed by #97 ?

**Comment by andrerom** [comment]
Mostly, so yew you can close this once it's merged.

Remaining issues:
- doing this is fromHash (but no clear alternative for now)
- why kernel called fromHash several times (4) in the profilings done, as opposed to just once

**Comment by emodric** [comment]
> Mostly, so yes you can close this once it's merged.

:+1: 

> why kernel called fromHash several times (4) in the profilings done, as opposed to just once

I'll try to investigate.

**Comment by emodric** [comment]
Mostly fixed by #97
